# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://github.com/realabbas/Github-Actions-React-Native
# https://blog.usejournal.com/automate-react-native-builds-with-github-actions-af54212d26dc
# https://blog.logrocket.com/react-native-ci-cd-using-github-actions/
# https://sonarcloud.io/project/configuration?analysisMode=GitHubActions&id=pritamkhose_GithubExplorerReactNative

name: react-native-android-build-apk

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      # Setup JDK
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: npm create bundle js
        run: |
          npm run bundle
      - name: Build Android Release apk
        run: |
          cd android && bash ./gradlew assembleRelease --stacktrace
      - name: Upload Artifact dev release apk
        uses: actions/upload-artifact@v2
        with:
          name: app-uat-release.apk
          path: android/app/build/outputs/apk/dev/release/app-uat-release.apk
          retention-days: 1
      - name: Upload Artifact qa release apk
        uses: actions/upload-artifact@v2
        with:
          name: app-uat-release.apk
          path: android/app/build/outputs/apk/qa/release/app-uat-release.apk
          retention-days: 2
      - name: Upload Artifact uat release apk
        uses: actions/upload-artifact@v2
        with:
          name: app-uat-release.apk
          path: android/app/build/outputs/apk/uat/release/app-uat-release.apk
          retention-days: 5
      - name: Upload Artifact bundle
        uses: actions/upload-artifact@v2
        with:
          name: index.android.bundle
          path: android/app/src/main/assets/index.android.bundle
          retention-days: 5